language: go
go:
 - 1.5
 - 1.6
 - 1.7
 - tip
script:
  - cd $GOPATH/src/github.com/ndege/shortr
  # - go get -d -v && go build -v && go test -i ./... && go test -test.v ./...
notifications:
  email: false
branches:
  only:
    - master
